import Head from 'next/head'
import { Inter } from '@next/font/google'
import {Navbar, Hero} from '../components'
import { Post } from '../components'
import PostList from '@/components/PostList'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ibx | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://api.fontshare.com/v2/css?f[]=general-sans@200,500,300,600,400&display=swap" rel="stylesheet"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Hero/>
      <PostList/>
    </>
  )
}
