import Head from 'next/head'
import {Navbar, Date, PostList} from '../../components'
import { useEffect, useState } from 'react'
import { useGetAllNewsQuery, useGetNewsByTitleQuery } from "@/store/apiSlice/newsApi";





const details = () => {

    const { data, error, isLoading, isError } = useGetNewsByTitleQuery({
        q:'title',
        apiKey:'d128a5d0636d4b81b69708bd2fbad56f'
      });

    return(
        <>
            <Head>
            <title>Ibx | News Details</title>
            <meta name="description" content="Generated by create next app" />
            <link href="https://api.fontshare.com/v2/css?f[]=general-sans@200,500,300,600,400&display=swap" rel="stylesheet"/>
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Navbar/>
            <div className='mx-auto max-w-7xl'>
              <h1>details</h1>
              <h1>{data?.article?.title}</h1>
               <p>{data?.article?.description}</p>  
            </div>
        </>
    )
}

// export const getServerSideProps = async (context) => {
//   const API_KEY = 'd128a5d0636d4b81b69708bd2fbad56f';
//   const ARTICLE_ID = 'article.source.id';

//   try {
//     const response = await axios.get(`https://newsapi.org/v2/everything?id=${ARTICLE_ID}&apiKey=${API_KEY}`);
//     const article = response.data.articles[0];
//     return {
//       props: {
//         article,
//       },
//     };
//   } catch (error) {
//     console.error(error);
//     return {
//       props: {
//         article: null,
//       },
//     };
//   }
// }

export default details
