import Head from 'next/head'
import {Navbar, Date, PostList} from '../../components'
import { useEffect, useState } from 'react'
import axios from 'axios'
import Link from 'next/link';
import { useGetAllNewsQuery, useGetNewsBySourceQuery } from "@/store/apiSlice/newsApi";

function allnews() {
  const [source, setSource] = useState('apple')

  const { data, error, isLoading, isError } = useGetNewsBySourceQuery({
    q:source,
    apiKey:'d128a5d0636d4b81b69708bd2fbad56f'
  });


  const handleFilter = (e) => {
    const value = e.target.value;
    setSource(value);
  }
  return (
    <>
    <Head>
      <title>Ibx | All News</title>
      <meta name="description" content="Generated by create next app" />
      <link href="https://api.fontshare.com/v2/css?f[]=general-sans@200,500,300,600,400&display=swap" rel="stylesheet"/>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <Navbar/>

    <div className='items-center mx-8 md:mx-auto md:max-w-7xl h-full py-20 2xl:px-16'>
        <div className='flex justify-between'>
            <p className='text-[30px] font-[500]'>Filter News</p>
            <select className='text-[17px] hover:cursor-pointer font-[500] hover:text-purple-800 ' onChange={handleFilter}>
              <option >Filter News By Source</option>
              <option value="apple">Apple</option>
              <option value="tesla">Tesla</option> 
              <option value="cnbc">CNBC</option>
              <option value="us">US</option>
              <option value="techCrunch">TechCrunch</option>
              <option value="Wall Street">Wall Street</option>
            </select>
        </div>
        <div className='grid grid-cols-2 md:grid-cols-4 gap-3 my-14'>
          
        {data?.articles?.map((item, id) => {
                return (
                  <>
                    <div className="max-w-lg mx-auto">
                      <div className="bg-white shadow-md border border-gray-200 rounded-lg max-w-sm mb-5" key={id}>
                          <a href={item.url}>
                            <img className="rounded-t-lg" src={item.urlToImage} alt="" />
                          </a>
                          <div className="p-5">
                              <a href={item.url}>
                                  <h5 className="text-gray-800 font-bold text-xl tracking-tight line-clamp-2 mb-2">{item.title}</h5>
                              </a>
                              <p className="font-normal text-gray-700 line-clamp-3 mb-3">{item.description}</p>
                              <a className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-3 py-2 text-center inline-flex items-center" href={item.url}>
                                  Read more
                              </a>
                          </div>
                      </div>
                      
                    </div>
                  </>
                );
              })}
        </div>
       </div>
  </>
  )
}

export default allnews
